### ISSUE TITLE
NoMethodError: undefined method `all_json' for #<Class:0x007f7f8ddc3098>

### ISSUE THREAD

**Issue by JohanAlvarado** [jackc/surus#16]
Hi, I was working fine with the gem, but later , appear this error, and the other helpers has the same error.

helper used:

all_json
find_json

error:
  NoMethodError: undefined method `all_json' for #<Class:0x007f7f8ddc3098>
from gems/activerecord-4.1.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'

pg version = psql (9.3.5)
ruby version = 2.1.5
rails version = 4.1.6
surus version = surus (0.2.0)
      activerecord (>= 3.1.0)

I put the gem into my Gemfile, and appear on my Gemfile.lock

**Comment by jackc** [comment]
Can you ```bundle update surus``` and try again. You are using surus 02.0 which predates the JSON feature.

**Comment by JohanAlvarado** [comment]
I ran bundle update surus, and this fix my issue, thank you
