### ISSUE TITLE
Include methods from model?

### ISSUE THREAD

**Issue by jemminger** [jackc/surus#36]
Is it possible to include methods as well as columns/associations?  

For example with `as_json`, you can include methods from the model:  `my_object.as_json(methods: [:this_method, :that_method])` and get back

```ruby
{
  id: 1,
  name: "Foo",
  this_method: "some value",
  that_method: "another value",
  ...
}
```

**Comment by jemminger** [comment]
Ah, thinking about it more I guess it's not possible, since you're retrieving straight from PG which would have no knowledge of the model's methods.

**Comment by jackc** [comment]
Correct. There's no way to do that without some serious hackery.
